apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-na
  name: web-nodeAff
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-na
  template:
    metadata:
      labels:
        app: web-na
    spec:
      containers:
      - image: mjbright/ckad-demo:alpine1
        name: ckad-demo
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              #- key: kubernetes.io/os=linux&kubernetes.io/arch=amd64
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
