apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test1
  name: test1
  namespace: example-monitor-pods
spec:
  serviceAccount: monitor-pods-acc
  containers:
  - image: mjbright/ckad-demo:1
    name: test1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


