kind: PersistentVolume
apiVersion: v1
metadata:
   name: pv0002
   labels:
      type: local

spec:
   capacity:
      storage: 20Gi
   accessModes:
   - ReadWriteMany
   hostPath:
       path: "/tmp/data02"
