apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-na
  name: web-node-aff
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-na
  template:
    metadata:
      labels:
        app: web-na
    spec:
      containers:
      - image: mjbright/ckad-demo:alpine1
        name: ckad-demo
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: team
                operator: In
                values:
                - staging
                - dev
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
