apiVersion: v1
kind: Service
metadata:
  labels:
    app: web1
  name: web1
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web1
  sessionAffinity: None
  type: ClusterIP
  clusterIP: 10.107.50.124
