apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ckad-demo-dep
  name: ckad-demo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckad-demo-dep
  template:
    metadata:
      labels:
        app: ckad-demo-dep
    spec:
      containers:
      - image: mjbright/ckad-demo:alpine1
        name: ckad-demo-dep
