apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: ckad-demo-dset
  name: ckad-demo-dset
spec:
  selector:
    matchLabels:
      app: ckad-demo-dset
  template:
    metadata:
      labels:
        app: ckad-demo-dset
    spec:
      containers:
      - image: mjbright/ckad-demo:alpine1
        name: ckad-demo-dset
