apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ckad-demo-sset
  name: ckad-demo-sset
spec:
  serviceName: ckad-demo-sset
  replicas: 10
  selector:
    matchLabels:
      app: ckad-demo-sset
  template:
    metadata:
      labels:
        app: ckad-demo-sset
    spec:
      containers:
      - image: mjbright/ckad-demo:alpine2
        name: ckad-demo-sset
