apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ckad-demo-blue
  name: ckad-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ckad-demo-blue
  type: ClusterIP
status:
  loadBalancer: {}
